config/routes.rb
MissionList::Application.routes.draw do

   root 'welcome#index'
 
   resources :users, :user_session
   

   get 'find_trips/', to: 'find_trips#index', as: :find_trips
   get 'find_trips/search', to: 'find_trips#search', as: :trip_search
   post 'find_trips/perform_search', to: 'find_trips#perform_search', as: :perform_trip_search
   
   get 'trips/show/:trip_id' => 'trips#show', as: :show_trip
   get 'trips/photo_ids_for_trip' => 'trips#get_photo_ids_for_trip', as: :photo_ids_for_trip
   get 'trips/view_my_trips' => 'trips#view_my_trips', as: :view_my_trips
   get 'trips/manage_trip/:trip_id' => 'trips#manage_trip', as: :manage_trip         
   get 'trips/add_trip' => 'trips#add_trip', as: :add_trip
   patch 'trips/update_trip/:trip_id' => 'trips#update_trip', as: :update_trip
   post 'trips/save_trip' => 'trips#save_trip', as: :save_trip
   get 'trips/follow_trip/:trip_id' => 'trips#follow_trip', as: :follow_trip
   get 'trips/stop_following_trip/:trip_id' => 'trips#stop_following_trip', as: :stop_following_trip
   get 'trips/sign_up_to_receive_updates' => 'trips#sign_up_to_receive_updates', as: :sign_up_to_receive_updates
   get 'trips/trip_feed' => 'trips#trip_feed', as: :trip_feed
   get 'trips/manage_email_list/:trip_id' => 'trips#manage_email_list', as: :manage_email_list
   get 'trips/new_email_recipient/:trip_id' => 'trips#new_email_recipient', as: :new_email_recipient
   post 'trips/save_email_recipient/:trip_id' => 'trips#save_email_recipient', as: :save_email_recipient
   delete 'trips/delete_email_recipient/:id' => 'trips#delete_email_recipient', as: :delete_email_recipient
   post 'trips/send_follower_notification_email' => 'trips#send_follower_notification_email', as: :send_follower_notification_email

   get 'trips/manage_team/:trip_id' => 'trips#manage_team', as: :manage_team
   get 'trips/get_fb_friends' => 'trips#get_fb_friends', as: :get_fb_friends
   post 'trips/invite_friends' => 'trips#invite_friends', as: :invite_friends
   delete 'trips/delete_team_member/trip_id=:trip_id&team_member_id=:team_member_id' => 'trips#delete_team_member', as: :delete_team_member

   scope '/trips/:trip_id' do 
     get 'newsletter/manage_newsletters' => 'newsletter#manage_newsletters', :as => :manage_newsletters
   end

   post 'newsletter/send_newsletter' => 'newsletter#send_newsletter', :as => :send_newsletter
   get 'newsletter/show/:id' => 'newsletter#show', :as => :show_newsletter

   get 'journal_entry/show/:id' => 'journal_entry#show', as: :show_journal_entry
   get 'journal_entry/photo_ids_for_entry' => 'journal_entry#get_photo_ids_for_entry', as: :photo_ids_for_entry
   get 'journal_entry/new/:trip_id' => 'journal_entry#new', as: :new_journal_entry
   get 'journal_entry/edit/:id' => 'journal_entry#edit', as: :edit_journal_entry
   post 'journal_entry/save' => 'journal_entry#save', as: :save_journal_entry
   get 'journal_entry/get_tags_for_user' => 'journal_entry#get_tags_for_user', as: :get_tags_for_user
   post 'journal_entry/update/:id' => 'journal_entry#update', as: :update_journal_entry
   get 'journal_entry/get_entry_info/:id' => 'journal_entry#get_entry_info', as: :get_entry_info
   delete 'journal_entry/delete/:id' => 'journal_entry#delete', as: :delete_journal_entry

   get 'images/resize_images' => 'image#resize_images', as: :resize_images

   get '/auth/facebook/callback', to: 'sessions#create'
   get '/auth/stripe_connect/callback', to: 'sessions#create_stripe'
   get 'signout' => 'sessions#destroy', as: :signout
   get 'signup' => 'sessions#signup', as: :signup
   get 'signin' => 'sessions#signin', as: :signin
   get 'disconnect_stripe' => 'sessions#destroy_stripe', as: :disconnect_stripe

   get 'user/show/:id' => 'user#show', as: :show_user
   get 'user/my_account' => 'user#my_account', as: :my_account
   get 'user/connect_to_stripe' => 'user#connect_to_stripe', as: :connect_to_stripe

   get 'donation/new/:to_user_id(/:trip_id)' => 'donation#new', as: :new_donation
   get 'donation/get_new_donation_data/:to_user_id' => 'donation#get_new_donation_data', as: :get_new_donation_data
   post 'donation/save/:to_user_id' => 'donation#save', as: :save_donation
   get 'donation/donation_complete' => 'donation#donation_complete', as: :donation_complete
   get 'donation/donation_error/:message' => 'donation#donation_error', as: :donation_error
   patch 'donation/update_thank_you_message' => 'donation#update_thank_you_message', as: :update_thank_you_message
   get 'donation/new_trip/:trip_id' => 'donation#new_trip', as: :new_trip_donation   
   get 'donation/get_trip_donation_data/:trip_id' => 'donation#get_trip_donation_data', as: :get_trip_donation_data
   post 'donation/make_trip_donation' => 'donation#make_trip_donation', as: :make_trip_donation
   get 'donation/view_my_donations' => 'donation#view_my_donations', as: :view_my_donations

   get 'admin/do_action' => 'admin#do_action', as: :do_action
   get 'admin/delete_doc/:doc_id' => 'admin#delete_doc'

   post 'welcome/send_welcome_email' => 'welcome#send_welcome_email', as: :send_welcome_email

end

app/models/trip.rb
class Trip < CouchRest::Model::Base	
	include FBInfo

	validates_presence_of :trip_name
	validates_numericality_of :price, :greater_than_or_equal_to => 0

	property :trip_name, String
	property :team_name, String
	property :start_date, Date
	property :end_date, Date
	property :description, String	
	property :teammate_user_ids, [String]
	property :user_id, String
	property :is_public_trip, TrueClass, :default => true
	property :doc_type, String
	property :num_journal_entries, Integer	
	property :price, String
	property :contact_email, String

	design do
		view :public_trips, :map => 
			"function(doc) { 
				if(doc['doc_type'] == 'trip') { 
					if(doc['is_public_trip'])
						emit (doc._id, doc);
				} 
			 }"
		view :all_trips, :map => 
			"function(doc) { 
				if(doc['doc_type'] == 'trip') { 					
						emit (doc._id, doc);
				} 
			 }"
	end



end

app/controllers/trips_controller.rb
class TripsController < ApplicationController		
	include ApplicationHelper
	include TripsHelper
	before_filter :authenticate, :only => 'send_welcome_email'
	protect_from_forgery with: :null_session

	before_filter :ensure_trip_owner, :only => [:manage_trip, :manage_team, :delete_team_member, :update_trip]

	def index

	end

	def show
		trip_id = params[:trip_id]

		@journal_entries = []
		@trip = Trip.get(trip_id)

		puts "TRIP ID: #{trip_id}"
		puts @trip.trip_name

		@teammates = get_team(@trip)

		JournalEntry.entries_for_trip.each do |j|
			@journal_entries << j if j.trip_id == trip_id && (!j.is_private || j.user_id == nullable_current_user_id)
		end

		@journal_entries = @journal_entries.sort_by{|j| j[:entry_date] }.reverse
	
	end

	def get_photo_ids_for_trip
		trip_id = params[:trip_id]

		journal_entries = []

		JournalEntry.entries_for_trip.each do |j|
			journal_entries << j if j.trip_id == trip_id
		end

		potential_photo_ids = []

		journal_entries.each do |j|
			potential_photo_ids = potential_photo_ids + j.photo_ids
		end

		#photo_ids = get_valid_photo_ids(potential_photo_ids)

		render :json => {:photo_ids => potential_photo_ids}

	end

	def view_my_trips
		@trips = []
		@trips_following = []

		Trip.all_trips.each do |t|			
			@trips << t if user_is_team_member(t)
			@trips_following << t if user_is_following_trip(t)
		end

	end

	def manage_trip
		@trip = Trip.get(params[:trip_id])
		@url = update_trip_path(@trip)
	end

	def manage_team
		@trip = Trip.get(params[:trip_id])
		@teammates = get_team_without_me(@trip)
	end

	def add_trip
		@trip = Trip.new
		@url = save_trip_path		
		render :manage_trip
	end

	def update_trip
		@trip = Trip.get(params[:trip_id])
		@trip.user_id = current_user.id		
		@trip.doc_type = "trip"

		if @trip.update_attributes(trip_attributes)
			redirect_to show_trip_path(@trip)
		else
			@url = update_trip_path(@trip)
			render "manage_trip"
		end

	end

	def save_trip
		@trip = Trip.new(trip_attributes)
		@trip.user_id = current_user.id
		@trip.doc_type = "trip"

		if @trip.save
			redirect_to show_trip_path(@trip)
		else
			@url = save_trip_path
			render :manage_trip

		end

	end

	def invite_friends
		trip = Trip.find(params[:trip_id])
		incoming_friend_ids = params[:friend_ids]

		teammate_user_ids = trip.teammate_user_ids;

		incoming_friend_ids.each do |id|
			unless trip.teammate_user_ids.include?(id)
				teammate_user_ids << id
			end

		end

		trip.update_attributes(:teammate_user_ids => teammate_user_ids)
		
		render :json => {success: true, teammate_user_ids: teammate_user_ids}
	end

	def delete_team_member
		trip = Trip.find(params[:trip_id])
		team_member_id = params[:team_member_id]

		puts 'deleting team member'
		puts team_member_id

		teammate_user_ids = trip.teammate_user_ids
		teammate_user_ids.delete(team_member_id)

		trip.update_attributes(:teammate_user_ids => teammate_user_ids)

		redirect_to manage_team_path(trip.id)

	end

	def follow_trip
		if(current_user.nil?)
			redirect_to :sign_up_to_receive_updates
		else
			puts params[:trip_id]
			trip = Trip.get(params[:trip_id])			
			trips_followed = current_user.trips_followed.nil? ? [] : current_user.trips_followed
			unless trips_followed.include?(trip.id)
				to_recipients = teammate_email_recipients(trip, current_user)

				if to_recipients.length > 0
					TripMailers.send_follow_notification(to_recipients, current_user.first_name, trip).deliver
				end

				trips_followed << trip.id

				puts trips_followed
				current_user.update_attributes(:trips_followed => trips_followed)
			end
			
			flash.notice = "You are now following #{trip.trip_name}!"

			redirect_to show_trip_path(params[:trip_id]) 

		end

	end

	def stop_following_trip
		trip_id = params[:trip_id]
		redirect_to show_trip_path(trip_id) if current_user.nil?

		trip = Trip.get(trip_id)

		trips_followed = current_user.trips_followed
		trips_followed.delete(trip_id)

		current_user.update_attributes(:trips_followed => trips_followed)

		flash.notice = "You are no longer following #{trip.trip_name}"
		redirect_to show_trip_path(trip_id)


	end

	def sign_up_to_receive_updates

	end

	def trip_feed
		@trips = []
		Trip.all_trips.each do |t|
			@trips << t if user_is_following_trip(t)
		end
	end

	def send_follower_notification_email
		trip = Trip.get(params[:trip_id])
		user = User.get(params[:user_id])

		to_recipients = teammate_email_recipients(trip, user)

		if to_recipients.length > 0
			TripMailers.send_follow_notification(to_recipients, user.first_name, trip).deliver
		end

		render :json => {:success => true, :message => 'Notification sent!'}
	end

	def teammate_email_recipients(trip, user)
		puts user.first_name
		teammates = team(trip, user)

		teammates.select { |t| !t.email.nil? and t.email.length > 0}.map { |t| t.email}
	end

	private
		def trip_attributes
			#not terribly fond of this hack, but it's the easiest way to convert the checkbox's weird way of
			#storing checked as "1" instead of true.
			is_public_trip = params[:trip][:is_public_trip]
			params[:trip][:is_public_trip] = is_public_trip == "1" ? true : false;

			params.require(:trip).permit!
		end

		def email_recipient_params
			params.require(:email_recipient).permit!
		end

		def authenticate
	    	authenticate_or_request_with_http_basic do |username, password|
		    username == ENV['API_USER'] && password == ENV['API_PASSWORD'] 
		end
	  end

end

app/helpers/trips_helper.rb
module TripsHelper

	def trip_date(input)		
		return input.strftime("%-b. %-d, %Y") if input != nil		
		return ""
	end

	def team(trip)
		team_with_or_without_me(trip, true)
  end

  def team_with_or_without_me(trip, with_me) 
      teammate_ids = []

      current_user_id = current_user.nil? ? -1 : current_user.id

      unless trip.user_id == current_user_id and !with_me
        teammate_ids << trip.user_id 
      end

      unless trip.teammate_user_ids.count == 0
        trip.teammate_user_ids.each do |user_id|
          unless user_id == current_user_id and !with_me
            teammate_ids << user_id
          end
        end
      end

      teammates = []

      teammate_ids.each do |teammate_id|
        team_member = User.get(teammate_id)
        teammates << team_member unless team_member.nil?
      end

      return teammates

  end

    def team_without_me(trip) 
      return get_team_with_or_without_me(trip, false)
    end

    def load_teammate_from_list(user_id, teammates) 
      return teammates.first { |t| t.id == user_id}
    end

end

app/views/trips/_trip_header.html.erb
<div class="row" id="trip_header_info">
				<div class="col-md-12">
					<h1><%= trip.trip_name %></h1>
						<% if !trip.team_name.to_s.empty? %>
							<div class="team_name">
								 <i class="fa fa-users"></i> <%= trip.team_name %>						
							</div>
							<% end %>

							<% if !trip.start_date.to_s.empty? and !trip.end_date.to_s.empty? %>
							<div class="trip_dates">
								 <i class="fa fa-calendar"></i> <%= trip_date(trip.start_date) %> - <%= trip_date(trip.end_date) %>				
							</div>

							<% end %>

				</div>
</div>

app/views/trips/_trip_list.html.erb
<div class="search_results list-group">
		<% trips.each do |trip| %>	
			<%= link_to show_trip_path(trip.id), :class => 'list-group-item trip_search_result' do %>			
				<h4 class="list-group-item-heading"><div class="title"><%= trip.trip_name %></div></h4>

					<div class="list-group-item-text">
						<div class="row">
							<div class="col-md-3">
								<% if !trip.team_name.to_s.empty? %>
								<div class="team_name">
									 <i class="fa fa-users"></i> <%= trip.team_name %>						
								</div>
								<% end %>

								<% if !trip.start_date.to_s.empty? and !trip.end_date.to_s.empty? %>
								<div class="trip_dates">
									 <i class="fa fa-calendar"></i> <%= trip_date(trip.start_date) %> - <%= trip_date(trip.end_date) %>				
								</div>
								<% end %>

								<% if trip.num_journal_entries %>
								<span class="label label-info"><%= trip.num_journal_entries %> <%= "entry".pluralize(trip.num_journal_entries) %></span>
								<% end %>

							</div>

							<div class="col-md-9">
								<% if !trip.description.to_s.empty? %>
									<p class="description"><%= trip.description %></p>
								<% end %>

							</div>

						</div>

					</div>
		

			<% end %>
			
		<% end %>
	</div>

app/views/trips/index.html.erb
<% @trips.each do |t| %>
	<%= t.trip_name %>


<% end %>

app/views/trips/manage_email_list.html.erb
<div class="container">
	<h1>Manage Email List</h1>

	<%= link_to 'New Recipient', new_email_recipient_path(@trip), :class => 'btn btn-primary' %>

	<table class="table">
		<thead>
			<tr>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Address</th>
				<th>Actions</th>
			</tr>
		</thead>

		<tbody>
			<% @email_recipients.each do |e| %>
				<tr>
					<td><%= e.first_name %></td>
					<td><%= e.last_name %></td>
					<td><%= e.address %></td>
					<td>
						<div class="btn-group">
							<%= link_to delete_email_recipient_path(e), :class => 'btn btn-danger', :method => 'delete' do %>
								<i class="fa fa-trash-o"></i> 
							<% end %>
						</div>

					</td>
				</tr>
			<% end %>
		</tbody>

	</table>

</div>

app/views/trips/manage_team.html.erb
<div class="container">
	
	<%= link_to "Back to my trip", show_trip_path(@trip.id), :class => 'btn btn-default' %>

	<h1>My Team 	<a href="#" id="invite_friends_button" class='btn btn-primary'><i class="fa fa-plus"></i> Invite Team Members</a></h1>
		
		<div class="list-group">

		<% @teammates.each do |t| %>
				<div class="list-group-item">					
			  			<img src="<%= t.photo_url %>"></img>
				  			<%= t.name %>
				  			<%= link_to "Remove from Team", delete_team_member_path(@trip.id, t.id), :class => 'btn btn-danger pull-right', :method => 'delete' %>
			  	</div>


		<% end %>
		</div>
	

	
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$("#invite_friends_button").click(function(e) {
			e.preventDefault();

			FB.ui({
			    method: 'apprequests',
			    message: 'Join me on my mission trip to <%= @trip.trip_name %>'
			}, function(response) {
				$.post('<%= invite_friends_path %>', {
					trip_id: '<%= @trip.id %>',
					friend_ids: response.to	
				}, function(result) {
					window.location.reload()
				});

			});
		});	
		
	});

</script>

app/views/trips/manage_trip.html.erb
<div class="container manage_trip">
		
	<%= form_for @trip, url: @url do |t| %>
		<%= render 'shared/error_messages', obj: @trip %>
		
		<div class="form-group">
			<%= t.label :trip_name %>
			<%= t.text_field :trip_name, :class => 'form-control' %>
		</div>

		<div class="form-group">
			<%= t.label :description %>
			<%= t.text_area :description, :class => 'form-control trip_description' %>
		</div>

		<div class="form-group">
			<%= t.label :team_name %>
			<%= t.text_field :team_name, :class => 'form-control' %>
		</div>

		<div class="form-group">			
			<%= t.label :start_date %>
			<div class="input-append date form_datetime">
				<%= t.text_field :start_date, :class => 'form-control' %>
				<span class="add-on"><i class="icon-th"></i></span>
			</div>
		</div>

		<div class="form-group">			
			<%= t.label :end_date %>
			<div class="input-append date form_datetime">
				<%= t.text_field :end_date, :class => 'form-control' %>
				<span class="add-on"><i class="icon-th"></i></span>
			</div>
		</div>

		<div class="form-group">
			<%= t.label :price %>
			<%= t.number_field :price, :class => 'form-control', :min => 0 %>
		</div>

		<div class="from-group">
			<%= t.label :contact_email %>
			<%= t.text_field :contact_email, :class => 'form-control' %>
		</div>

		<div class="form-group">
			<%= t.label "Public Trip?" %>
			<%= t.check_box :is_public_trip %><br />
			<div class="alert alert-info">
			<span class="label label-default">Heads up!</span>
				A public trip allows anyone to
				<ul>
					<li>See and share trip entries and photos</li>					
					<li>Donate to your trip</li>
				</ul>
			</div>
		</div>
		
		<%= t.submit 'Save', :class => 'btn btn-primary' %>



	<% end %>


</div>


<script type="text/javascript">
  $(document).ready(function(){
     $(".form_datetime").datetimepicker({
        format: "yyyy-mm-dd",
        minView: 2,
        maxView: 2

    });
  })
</script>

app/views/trips/new_email_recipient.html.erb
<div class='container'>
	<h1>New Email Recipient</h1>

	<%= render 'shared/error_messages', obj: @recipient %>

	<%= form_for @recipient, :url => save_email_recipient_path(@trip) do |e| %>
		<div class="form-group">
			<%= e.label :first_name, :class => 'control-label' %>
			<%= e.text_field :first_name, :class => 'form-control' %>
		</div>

		<div class="form-group">
			<%= e.label :last_name, :class => 'control-label' %>
			<%= e.text_field :last_name, :class => 'form-control' %>
		</div>

		<div class='form-group'>
			<%= e.label :address, :class => 'control-label' %>
			<%= e.text_field :address, :class => 'form-control' %>

		</div>

		<%= e.submit 'Save', :class => 'btn btn-primary' %>

	<% end %>

</div>

app/views/trips/show.html.erb
<% content_for :meta_tags do %>
	<meta property="og:title" content="<%= @trip.trip_name %>" />
	<meta property="og:description" content="<%= @trip.description %>" />
	<meta property="og:type" content="<%= ENV['FACEBOOK_NAMESPACE_PREFIX'] %>:trip" />
	<meta property="og:url" content="<%= show_trip_url(@trip.id) %>" />
	<meta property="og:image" content="<%= image_url('logo.png') %>" />
<% end %>

<div class="container">

	<% if flash[:notice] %>
    	<div class="alert alert-success"><%= flash[:notice] %></div>
  	<% end %>

	<div class="row">
		<div class="col-md-9">
			
			<%= render 'trips/trip_header', trip: @trip %>

				<%# if user_belongs_to_trip(@trip) %>	
				<%# link_to new_journal_entry_path(@trip.id), :class => 'btn btn-primary' do %> 
				<!-- <i class="fa fa-plus"></i> New Entry<%# end %> -->
				<%# end %>

				<%# if user_belongs_to_trip(@trip) %>
				<!-- 	<span class="dropdown">
						<button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
							Trip Actions
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" role="menu">
							<li> -->
								<%# link_to manage_trip_path(@trip), :role => 'menuitem' do %>
								<!-- <i class="fa fa-pencil"></i> Manage Trip -->
							<%# end %>
							<!-- </li> -->
							<!-- <li> -->
								<%# link_to manage_team_path(@trip),:role => 'menuitem' do %>
								<!-- <i class="fa fa-users"></i> Manage Team -->
							<%# end %>
							<!-- </li> -->

							<!-- <li> -->
								<%# link_to manage_newsletters_path(@trip), :role => 'menuitem' do %>
									<!-- <i class="fa fa-envelope"></i> Manage Newsletters  -->
								<%# end %>
							<!-- </li> -->
						<!-- </ul> -->
					<!-- </span> -->

					<%# end %>

				
					<div class="btn-group pull-right">
						
						<%= link_to new_trip_donation_path(@trip.id), :class => 'btn btn-link' do %>
							<i class="fa fa-heart"></i> Support
						<% end %>

						<% if !user_is_following_trip(@trip) %>
							<%= link_to follow_trip_path(@trip.id), :class => 'btn btn-link' do %>
								<i class="fa fa-bookmark"></i> Follow
							<% end %>

						<% else %>
							<%= link_to stop_following_trip_path(@trip.id), :class => 'btn btn-link btn-danger' do %>
								<i class="fa fa-stop"></i> Unfollow 
							<% end %>						
	
						<% end %>

						<a class="btn btn-link pull-right" id="share_button"><i class="fa fa-share"></i> Share</a>
					</div>
			<div class="entries">
				<h3>Updates</h3>
				 
				<% @journal_entries.each do |j| %>
						<div class="row entry">
							
								<div class="col-md-2">
									<%= render 'shared/entry_date', entry_date: j.entry_date %>
								</div>

								<div class="col-md-9 well">
									<%= render 'shared/profile_info', profile_info: load_teammate_from_list(j.user_id, @teammates) %>

									<p class="preserve_whitespace_paragraph"><%= paragraph_limiter j.entry_description %></p>	

									<%= link_to "View", show_journal_entry_path(j.id), :class => 'btn btn-primary' %>


								</div>		
						</div>
				<% end %>
			</div>


		</div>

		<div class="col-md-3 well well-sm">
			
			<h3 class="text-center">About This Trip</h3>

			<% if !@trip.description.nil? and @trip.description.length > 0 %>
				<div>
					<b>Description</b><br />
					<%= @trip.description %>
				</div>
				<br />
			<% end %>

			<% if !@trip.price.nil? and @trip.price.length > 0 %>
				<strong>Price</strong><br />
				$<%= @trip.price %>	
				<br />
			<% end %>

		
			<h3 class="text-center">Meet the Team</h3>
			<%= render "team/team_grid", teammates: @teammates %>

			<h3 class="text-center">Photos</h3>

			<div id="gallery" class="text-center">
						
			</div>
			
		</div>



</div>

<%= render 'shared/photo_template' %>

<script type="text/javascript">

	$(document).ready(function() {				

		var target = document.getElementById('gallery');
		var spinner = new Spinner().spin(target);	


		$.get("<%= photo_ids_for_trip_path %>", {trip_id: "<%= @trip.id %>"}, function(data) {
			_.each(data.photo_ids, function(photo_id) {				
				var file_name = photo_id + ".jpg";
				var photo_template = $("#photo_template").html();
				var html = Mustache.render(photo_template, {file_name: file_name});				
				$("#gallery").append(html);								
			});

			$('#gallery').photobox('a',{ time:0 });
			spinner.stop();
		});

		$("#share_button").click(function() {
			<%= fb_share('trip', show_trip_url(@trip.id)) %>
		});

	});

	

</script>

app/views/trips/sign_up_to_receive_updates.html.erb
<div class="container">
<h1>Sign Up</h1>
	<p>You'll need to sign up or sign in with Facebook to receive updates to this trip. Don't worry! It's quick, easy, and we won't post anything without your permission.</p>

	<%= link_to 'Sign Up or Sign In', '/auth/facebook', :class => 'btn btn-primary' %>
</div>

app/views/trips/trip_feed.html.erb
<div class="container">
	<h1>Trip Updates</h1>

</div>

app/views/trips/trip_followed.html.erb
<div class='container'>
	<h1>You're Now Following <%= @trip.trip_name %>!</h1>



</div>

app/views/trips/view_my_trips.html.erb
<div class="container">	
	<fieldset>
		<legend>Trips I'm a Part of</legend>

			<%# link_to add_trip_path, :class => 'btn btn-primary with_bottom_margin' do %>
			<!-- 	<i class="fa fa-plus"></i> Add a Trip -->
			<%# end %>
			<%= render "trip_list", trips: @trips %>
	</fieldset>

	<fieldset>
		<legend>Trips I'm following</legend>
		<%= render "trip_list", trips: @trips_following %>
	</fieldset>

</div>