config/routes.rb
MissionList::Application.routes.draw do

   root 'welcome#index'
 
   resources :users, :user_session
   

   get 'find_trips/', to: 'find_trips#index', as: :find_trips
   get 'find_trips/search', to: 'find_trips#search', as: :trip_search
   post 'find_trips/perform_search', to: 'find_trips#perform_search', as: :perform_trip_search
   
   get 'trips/show/:trip_id' => 'trips#show', as: :show_trip
   get 'trips/photo_ids_for_trip' => 'trips#get_photo_ids_for_trip', as: :photo_ids_for_trip
   get 'trips/view_my_trips' => 'trips#view_my_trips', as: :view_my_trips
   get 'trips/manage_trip/:trip_id' => 'trips#manage_trip', as: :manage_trip         
   get 'trips/add_trip' => 'trips#add_trip', as: :add_trip
   patch 'trips/update_trip/:trip_id' => 'trips#update_trip', as: :update_trip
   post 'trips/save_trip' => 'trips#save_trip', as: :save_trip
   get 'trips/follow_trip/:trip_id' => 'trips#follow_trip', as: :follow_trip
   get 'trips/stop_following_trip/:trip_id' => 'trips#stop_following_trip', as: :stop_following_trip
   get 'trips/sign_up_to_receive_updates' => 'trips#sign_up_to_receive_updates', as: :sign_up_to_receive_updates
   get 'trips/trip_feed' => 'trips#trip_feed', as: :trip_feed
   get 'trips/manage_email_list/:trip_id' => 'trips#manage_email_list', as: :manage_email_list
   get 'trips/new_email_recipient/:trip_id' => 'trips#new_email_recipient', as: :new_email_recipient
   post 'trips/save_email_recipient/:trip_id' => 'trips#save_email_recipient', as: :save_email_recipient
   delete 'trips/delete_email_recipient/:id' => 'trips#delete_email_recipient', as: :delete_email_recipient
   post 'trips/send_follower_notification_email' => 'trips#send_follower_notification_email', as: :send_follower_notification_email

   get 'trips/manage_team/:trip_id' => 'trips#manage_team', as: :manage_team
   get 'trips/get_fb_friends' => 'trips#get_fb_friends', as: :get_fb_friends
   post 'trips/invite_friends' => 'trips#invite_friends', as: :invite_friends
   delete 'trips/delete_team_member/trip_id=:trip_id&team_member_id=:team_member_id' => 'trips#delete_team_member', as: :delete_team_member

   scope '/trips/:trip_id' do 
     get 'newsletter/manage_newsletters' => 'newsletter#manage_newsletters', :as => :manage_newsletters
   end

   post 'newsletter/send_newsletter' => 'newsletter#send_newsletter', :as => :send_newsletter
   get 'newsletter/show/:id' => 'newsletter#show', :as => :show_newsletter

   get 'journal_entry/show/:id' => 'journal_entry#show', as: :show_journal_entry
   get 'journal_entry/photo_ids_for_entry' => 'journal_entry#get_photo_ids_for_entry', as: :photo_ids_for_entry
   get 'journal_entry/new/:trip_id' => 'journal_entry#new', as: :new_journal_entry
   get 'journal_entry/edit/:id' => 'journal_entry#edit', as: :edit_journal_entry
   post 'journal_entry/save' => 'journal_entry#save', as: :save_journal_entry
   get 'journal_entry/get_tags_for_user' => 'journal_entry#get_tags_for_user', as: :get_tags_for_user
   post 'journal_entry/update/:id' => 'journal_entry#update', as: :update_journal_entry
   get 'journal_entry/get_entry_info/:id' => 'journal_entry#get_entry_info', as: :get_entry_info
   delete 'journal_entry/delete/:id' => 'journal_entry#delete', as: :delete_journal_entry

   get 'images/resize_images' => 'image#resize_images', as: :resize_images

   get '/auth/facebook/callback', to: 'sessions#create'
   get '/auth/stripe_connect/callback', to: 'sessions#create_stripe'
   get 'signout' => 'sessions#destroy', as: :signout
   get 'signup' => 'sessions#signup', as: :signup
   get 'signin' => 'sessions#signin', as: :signin
   get 'disconnect_stripe' => 'sessions#destroy_stripe', as: :disconnect_stripe

   get 'user/show/:id' => 'user#show', as: :show_user
   get 'user/my_account' => 'user#my_account', as: :my_account
   get 'user/connect_to_stripe' => 'user#connect_to_stripe', as: :connect_to_stripe

   get 'donation/new/:to_user_id(/:trip_id)' => 'donation#new', as: :new_donation
   get 'donation/get_new_donation_data/:to_user_id' => 'donation#get_new_donation_data', as: :get_new_donation_data
   post 'donation/save/:to_user_id' => 'donation#save', as: :save_donation
   get 'donation/donation_complete' => 'donation#donation_complete', as: :donation_complete
   get 'donation/donation_error/:message' => 'donation#donation_error', as: :donation_error
   patch 'donation/update_thank_you_message' => 'donation#update_thank_you_message', as: :update_thank_you_message
   get 'donation/new_trip/:trip_id' => 'donation#new_trip', as: :new_trip_donation   
   get 'donation/get_trip_donation_data/:trip_id' => 'donation#get_trip_donation_data', as: :get_trip_donation_data
   post 'donation/make_trip_donation' => 'donation#make_trip_donation', as: :make_trip_donation
   get 'donation/view_my_donations' => 'donation#view_my_donations', as: :view_my_donations

   get 'admin/do_action' => 'admin#do_action', as: :do_action
   get 'admin/delete_doc/:doc_id' => 'admin#delete_doc'

   post 'welcome/send_welcome_email' => 'welcome#send_welcome_email', as: :send_welcome_email

end

app/models/journal_entry.rb
class JournalEntry < CouchRest::Model::Base	
	include FBInfo

	property :trip_id, String
	property :user_id, String	
	property :entry_description, String
	property :entry_date, DateTime
	property :is_private, TrueClass
	property :photo_ids, [String]
	property :tag_ids, [String]
	property :doc_type, String

	attr_reader :user_token
	 
	design do 
		view :entries_for_trip, :map => 
			"function(doc) { 
				if(doc['doc_type'] == 'journal_entry') {				
						emit (doc._id, doc);
				} 
			 }"

	end

end

app/controllers/journal_entry_controller.rb
class JournalEntryController < ApplicationController
	include ApplicationHelper

	before_filter :ensure_correct_team_member, :only => [:edit, :delete, :update]
	before_filter :ensure_team_member, :only => [:new]


	def show
		journal_entry_id = params[:id]

		@entry = JournalEntry.get(journal_entry_id) 

		@tags = []

		unless @entry.tag_ids.nil?
			@entry.tag_ids.each do |tag_id|
				@tags << Tag.get(tag_id)			
			end
		end
		
		@trip = Trip.get(@entry.trip_id)

	end

	def get_photo_ids_for_entry		
		entry = JournalEntry.get(params[:journal_entry_id])
		photo_ids = get_valid_photo_ids(entry.photo_ids)

		render :json => {:photo_ids => photo_ids}

	end

	def new
		@trip = Trip.find(params[:trip_id])
		@id = -1
		@url = save_journal_entry_path(@trip.id)
		@page_title = "New Entry"

		render :action => "new_edit"
	end

	def edit		
		entry = JournalEntry.find(params[:id])
		@id = entry.id
		@trip = Trip.get(entry.trip_id)
		@url = update_journal_entry_path(params[:id])
		@page_title = "New Entry"

		render :action => "new_edit"
	end

	def save		
		entry_params = get_entry_params	
		entry = JournalEntry.new(entry_params)	
		entry.tag_ids = assign_tags(params[:tags])
		
		entry.save!

		redirect_url = show_journal_entry_url(entry.id)		
		render :json => {:redirect_url => redirect_url}

	end

	def delete
		entry = JournalEntry.get(params[:id])
		entry.destroy

		redirect_to show_trip_path(entry.trip_id)
	end

	def update
		entry_params = get_entry_params	
		entry = JournalEntry.get(params[:id])	
		entry.tag_ids = assign_tags(params[:tags])
		
		entry.update_attributes(entry_params)

		redirect_url = show_journal_entry_url(entry.id)		
		render :json => {:redirect_url => redirect_url}
	end

	def assign_tags(tags)
		tag_ids = []
		
		unless tags.nil?
			tags.each do |t|
				if t[:id] == -1
					new_tag = Tag.new 
					new_tag.tag_name = t[:tag_name]
					new_tag.doc_type = "tag"
					new_tag.user_id = current_user.id

					new_tag.save
					tag_ids << new_tag.id
				else
					tag_ids << t[:id]
				end
			end
		end

		return tag_ids

	end


	def get_tags_for_user 
		tags = []
		Tag.all_tags.each do |t|
			tags << t if t.user_id == current_user.id
		end

		render :json => {:tags => tags}

	end

	def get_entry_info
		entry = JournalEntry.get(params[:id])

		tags = []

		unless entry.tag_ids.nil? 
			entry.tag_ids.each do |tag_id|
				tags << Tag.get(tag_id)
			end
		end

		render :json => {:entry => entry, :tags => tags}

	end

	private

		def get_entry_params
			param = params.require(:entry).permit!
			param.merge({:user_id => current_user.id, :doc_type => 'journal_entry'})
		end



end

app/helpers/journal_entry_helper.rb
module JournalEntryHelper
end

app/views/journal_entry/new_edit.html.erb
<div class="container" id="journal_entry_form" ng-app="journal_entry_app" ng-controller="JournalEntryController" ng-init="initialize('<%= @trip.id %>', '<%= @id %>', '<%= @url %>')">

	<% back_url = @id == -1 ? show_trip_path(@trip.id) : show_journal_entry_path(@id) %>
	<% back_name = @id == -1 ? "Back to Trip" : "Back to Entry" %>
	
	<%= link_to back_url, :class => 'btn btn-default' do %>
		<i class="fa fa-chevron-left"></i> <%= back_name %>
	<% end %>

	<h1>{{entry.id == -1 ? "New Entry" : "Edit Entry"}}</h1>

	<form name="journal_entry_form" no-validate>
		<div class="form-group">
			<label class="control-label">Entry Date</label>
			<div class="input-append date form_datetime">
    			<input class="form-control" type="text" ng-model="entry.entry_date" readonly required>
    			<span class="add-on"><i class="icon-th"></i></span>
			</div>
		</div>

		<div class="form-group">
			<label class="control-label">Description</label>
			<textarea class="form-control entry_description" ng-model="entry.entry_description" required></textarea>
		</div>

		<div class="tags form-group">				
			<label class="control-label">Tags</label>						
			 <tags-input ng-model="entry.tags" class="bootstrap" display-property="tag_name" on-tag-added="add_tag($tag)">
			 	<auto-complete source="load_tags($query)"></auto-complete>        				
			</tags-input>
		</div>
		
		<div class="form-group">
			<label>Make Private? <input type="checkbox" ng-model="entry.is_private" /></label>
		</div>

		<button ng-disabled="!journal_entry_form.$valid" ng-click="save(journal_entry_form)" class='btn btn-primary'>Save</button>

	</form>

</div>



<script type="text/javascript">
  $(document).ready(function(){
    $(".form_datetime").datetimepicker({
        format: "mm/dd/yyyy HH:ii P",
        showMeridian: true,
    });
  })
</script>

app/views/journal_entry/show.html.erb
<% content_for :meta_tags do %>
	<meta property="og:title" content="<%= @trip.trip_name %>" />
	<meta property="og:description" content="<%= @entry.entry_description %>" />
	<meta property="og:type" content="<%= ENV['FACEBOOK_NAMESPACE_PREFIX'] %>:journal_entry" />
	<meta property="og:url" content="<%= show_journal_entry_url(@entry.id) %>" />
	<meta property="og:image" content="<%= image_url('logo.png') %>" />

<% end %>
	
<div class="container">	
	
	<%= link_to show_trip_path(@trip.id), :class => 'btn btn-default' do %>
		<i class="fa fa-chevron-left"></i> Back to Trip
	<% end %>

	<%= render 'trips/trip_header', trip: @trip %>

	<div class="btn-group with_bottom_margin">

		<% if user_owns_journal_entry(@entry) %>

			<%= link_to edit_journal_entry_path(@entry.id), :class => 'btn btn-default' do %>
				<i class="fa fa-pencil"></i> Edit Entry
			<% end %>
			<%= link_to delete_journal_entry_path(@entry.id), :class => 'btn btn-danger', :method => 'delete' do %>
				<i class="fa fa-trash-o"></i> Delete Entry
			<% end %>

		<% end %>

	</div>

	<div class="row">
		<div class="col-md-9">
			<div class="row">
				<div class="col-md-2">
					<%= render 'shared/entry_date', entry_date: @entry.entry_date %>
				</div>

				<div class="col-md-9 well">		
					<a class="btn btn-link pull-right" id="share_button"><i class="fa fa-share"></i> Share</a>
					<%= render 'shared/profile_info', profile_info: profile_info(@entry.user_id) %>					
					<p class="preserve_whitespace_paragraph"><%= @entry.entry_description %></p>

					<% @tags.each do |t| %>
						<span class="label label-info"><i><%= t.tag_name %></i></span>
					<% end %>	
					
					

				</div>
			</div>
		</div>

		<div class="col-md-3 well well-sm">
			<h4>Photos</h4>

			<div id="gallery">
				
			</div>

		</div>

	</div>
	
</div>

<%= render 'shared/photo_template' %>



<script type="text/javascript">
	$(document).ready(function() {	

		var target = document.getElementById('gallery');
		var spinner = new Spinner().spin(target);	

		$.get("<%= photo_ids_for_entry_path %>", {journal_entry_id: "<%= @entry.id %>"}, function(data) {
			_.each(data.photo_ids, function(photo_id) {				
				var file_name = photo_id + ".jpg";
				var photo_template = $("#photo_template").html();
				var html = Mustache.render(photo_template, {file_name: file_name});				
				$("#gallery").append(html);								
			});

			$('#gallery').photobox('a',{ time:0 });
			spinner.stop();
		});

		$("#share_button").click(function() {
			<%= fb_share('journal_entry', show_journal_entry_url(@entry.id)) %>
		});


	});

</script>