config/routes.rb
MissionList::Application.routes.draw do

   root 'welcome#index'
 
   resources :users, :user_session
   

   get 'find_trips/', to: 'find_trips#index', as: :find_trips
   get 'find_trips/search', to: 'find_trips#search', as: :trip_search
   post 'find_trips/perform_search', to: 'find_trips#perform_search', as: :perform_trip_search
   
   get 'trips/show/:trip_id' => 'trips#show', as: :show_trip
   get 'trips/photo_ids_for_trip' => 'trips#get_photo_ids_for_trip', as: :photo_ids_for_trip
   get 'trips/view_my_trips' => 'trips#view_my_trips', as: :view_my_trips
   get 'trips/manage_trip/:trip_id' => 'trips#manage_trip', as: :manage_trip         
   get 'trips/add_trip' => 'trips#add_trip', as: :add_trip
   patch 'trips/update_trip/:trip_id' => 'trips#update_trip', as: :update_trip
   post 'trips/save_trip' => 'trips#save_trip', as: :save_trip
   get 'trips/follow_trip/:trip_id' => 'trips#follow_trip', as: :follow_trip
   get 'trips/stop_following_trip/:trip_id' => 'trips#stop_following_trip', as: :stop_following_trip
   get 'trips/sign_up_to_receive_updates' => 'trips#sign_up_to_receive_updates', as: :sign_up_to_receive_updates
   get 'trips/trip_feed' => 'trips#trip_feed', as: :trip_feed
   get 'trips/manage_email_list/:trip_id' => 'trips#manage_email_list', as: :manage_email_list
   get 'trips/new_email_recipient/:trip_id' => 'trips#new_email_recipient', as: :new_email_recipient
   post 'trips/save_email_recipient/:trip_id' => 'trips#save_email_recipient', as: :save_email_recipient
   delete 'trips/delete_email_recipient/:id' => 'trips#delete_email_recipient', as: :delete_email_recipient
   post 'trips/send_follower_notification_email' => 'trips#send_follower_notification_email', as: :send_follower_notification_email

   get 'trips/manage_team/:trip_id' => 'trips#manage_team', as: :manage_team
   get 'trips/get_fb_friends' => 'trips#get_fb_friends', as: :get_fb_friends
   post 'trips/invite_friends' => 'trips#invite_friends', as: :invite_friends
   delete 'trips/delete_team_member/trip_id=:trip_id&team_member_id=:team_member_id' => 'trips#delete_team_member', as: :delete_team_member

   scope '/trips/:trip_id' do 
     get 'newsletter/manage_newsletters' => 'newsletter#manage_newsletters', :as => :manage_newsletters
   end

   post 'newsletter/send_newsletter' => 'newsletter#send_newsletter', :as => :send_newsletter
   get 'newsletter/show/:id' => 'newsletter#show', :as => :show_newsletter

   get 'journal_entry/show/:id' => 'journal_entry#show', as: :show_journal_entry
   get 'journal_entry/photo_ids_for_entry' => 'journal_entry#get_photo_ids_for_entry', as: :photo_ids_for_entry
   get 'journal_entry/new/:trip_id' => 'journal_entry#new', as: :new_journal_entry
   get 'journal_entry/edit/:id' => 'journal_entry#edit', as: :edit_journal_entry
   post 'journal_entry/save' => 'journal_entry#save', as: :save_journal_entry
   get 'journal_entry/get_tags_for_user' => 'journal_entry#get_tags_for_user', as: :get_tags_for_user
   post 'journal_entry/update/:id' => 'journal_entry#update', as: :update_journal_entry
   get 'journal_entry/get_entry_info/:id' => 'journal_entry#get_entry_info', as: :get_entry_info
   delete 'journal_entry/delete/:id' => 'journal_entry#delete', as: :delete_journal_entry

   get 'images/resize_images' => 'image#resize_images', as: :resize_images

   get '/auth/facebook/callback', to: 'sessions#create'
   get '/auth/stripe_connect/callback', to: 'sessions#create_stripe'
   get 'signout' => 'sessions#destroy', as: :signout
   get 'signup' => 'sessions#signup', as: :signup
   get 'signin' => 'sessions#signin', as: :signin
   get 'disconnect_stripe' => 'sessions#destroy_stripe', as: :disconnect_stripe

   get 'user/show/:id' => 'user#show', as: :show_user
   get 'user/my_account' => 'user#my_account', as: :my_account
   get 'user/connect_to_stripe' => 'user#connect_to_stripe', as: :connect_to_stripe

   get 'donation/new/:to_user_id(/:trip_id)' => 'donation#new', as: :new_donation
   get 'donation/get_new_donation_data/:to_user_id' => 'donation#get_new_donation_data', as: :get_new_donation_data
   post 'donation/save/:to_user_id' => 'donation#save', as: :save_donation
   get 'donation/donation_complete' => 'donation#donation_complete', as: :donation_complete
   get 'donation/donation_error/:message' => 'donation#donation_error', as: :donation_error
   patch 'donation/update_thank_you_message' => 'donation#update_thank_you_message', as: :update_thank_you_message
   get 'donation/new_trip/:trip_id' => 'donation#new_trip', as: :new_trip_donation   
   get 'donation/get_trip_donation_data/:trip_id' => 'donation#get_trip_donation_data', as: :get_trip_donation_data
   post 'donation/make_trip_donation' => 'donation#make_trip_donation', as: :make_trip_donation
   get 'donation/view_my_donations' => 'donation#view_my_donations', as: :view_my_donations

   get 'admin/do_action' => 'admin#do_action', as: :do_action
   get 'admin/delete_doc/:doc_id' => 'admin#delete_doc'

   post 'welcome/send_welcome_email' => 'welcome#send_welcome_email', as: :send_welcome_email

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mission List</title>
  <%= stylesheet_link_tag    "application", media: "all" %>  
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag "application" %>    
  <%= javascript_include_tag "http://underscorejs.org/underscore-min.js" %>
  <%= javascript_include_tag "http://fgnass.github.io/spin.js/spin.min.js" %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">    
  <%= yield(:meta_tags) %>
  <link rel="shortcut icon" href="<%= image_path('favicon.ico') %>">

  <%= analytics_init if Rails.env.production? %>

</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to root_path, :class => "navbar-brand" do %>      
        <%= image_tag "logo_small.png" %> Mission List
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= nav_link_to 'Home', root_path, 'welcome' %>

        <%= nav_link_to 'Find Trips', find_trips_path, 'find_trips' %>

        <% if current_user %>
          <%= nav_link_to 'My Trips', view_my_trips_path, 'trips' %>          
          <%= nav_link_to 'Donations', view_my_donations_path, 'donation' %>
        <% end %>


      </ul>		   
     
      <% if current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag current_user.photo_url %>
              <%= "#{current_user.first_name} #{current_user.last_name}" %> <b class="caret"></b>
            </a>


            <ul class="dropdown-menu">
               <li><%= link_to 'My Profile', show_user_path(current_user.id) %></li>
               <li><%= link_to 'My Account', my_account_path %></li>
               <li><%= link_to 'Sign Out', signout_path %></li>

            </ul>
          </li>

        </ul>

       

      <% else %>
        <div class="btn-group navbar-right">
          <%= link_to 'Sign In', '/auth/facebook', :class => 'btn btn-default navbar-btn' %>          
          <%= link_to 'Sign Up', '/auth/facebook', :class => 'btn btn-primary navbar-btn' %>
        </div>
      <% end %>

    </div>   
      
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

  <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : "<%= ENV['FACEBOOK_KEY'] %>",
          xfbml      : true,
          cookie     : true,
          version    : 'v2.0'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));

      $(document).ready(function() {
        // $("#sign_in_button").click(function(e) {
        //     e.preventDefault();

        //     FB.login(function(response) {
        //           if (response.authResponse) {
        //             $.getJSON('/auth/facebook/callback', function(json) {
        //                 window.location.reload("<%= root_path %>");
        //             });
        //           }
        //         }, { scope: 'email,read_stream' });
        //     });
      });


    </script>


</body>
</html>